/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as YorlingoRouteImport } from './routes/yorlingo'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountDownloadsRouteImport } from './routes/account.downloads'
import { Route as AccountLibraryRouteImport } from './routes/account.library'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountPaymentMethodsRouteImport } from './routes/account.payment-methods'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'
import { Route as CheckoutConfirmationRouteImport } from './routes/checkout.confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const YorlingoRoute = YorlingoRouteImport.update({
  id: '/yorlingo',
  path: '/yorlingo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDownloadsRoute = AccountDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLibraryRoute = AccountLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPaymentMethodsRoute = AccountPaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutConfirmationRoute = CheckoutConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CheckoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/account': typeof AccountIndexRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payment-methods': typeof AccountPaymentMethodsRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/checkout/confirmation': typeof CheckoutConfirmationRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/resources'
    | '/reviews'
    | '/yorlingo'
    | '/account/addresses'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/profile'
    | '/account/settings'
    | '/account/wishlist'
    | '/books/$slug'
    | '/checkout/confirmation'
    | '/account/'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/resources'
    | '/reviews'
    | '/yorlingo'
    | '/account/addresses'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/profile'
    | '/account/settings'
    | '/account/wishlist'
    | '/books/$slug'
    | '/checkout/confirmation'
    | '/account'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/resources'
    | '/reviews'
    | '/yorlingo'
    | '/account/addresses'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/payment-methods'
    | '/account/profile'
    | '/account/settings'
    | '/account/wishlist'
    | '/books/$slug'
    | '/checkout/confirmation'
    | '/account/'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  BundlesRoute: typeof BundlesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  YorlingoRoute: typeof YorlingoRoute
  BooksSlugRoute: typeof BooksSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yorlingo': {
      id: '/yorlingo'
      path: '/yorlingo'
      fullPath: '/yorlingo'
      preLoaderRoute: typeof YorlingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/downloads': {
      id: '/account/downloads'
      path: '/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AccountDownloadsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/library': {
      id: '/account/library'
      path: '/library'
      fullPath: '/account/library'
      preLoaderRoute: typeof AccountLibraryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/payment-methods': {
      id: '/account/payment-methods'
      path: '/payment-methods'
      fullPath: '/account/payment-methods'
      preLoaderRoute: typeof AccountPaymentMethodsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/confirmation': {
      id: '/checkout/confirmation'
      path: '/confirmation'
      fullPath: '/checkout/confirmation'
      preLoaderRoute: typeof CheckoutConfirmationRouteImport
      parentRoute: typeof CheckoutRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountDownloadsRoute: typeof AccountDownloadsRoute
  AccountLibraryRoute: typeof AccountLibraryRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentMethodsRoute: typeof AccountPaymentMethodsRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressesRoute: AccountAddressesRoute,
  AccountDownloadsRoute: AccountDownloadsRoute,
  AccountLibraryRoute: AccountLibraryRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentMethodsRoute: AccountPaymentMethodsRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutConfirmationRoute: typeof CheckoutConfirmationRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutConfirmationRoute: CheckoutConfirmationRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  BundlesRoute: BundlesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  YorlingoRoute: YorlingoRoute,
  BooksSlugRoute: BooksSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
