/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as YorlingoRouteImport } from './routes/yorlingo'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountDownloadsRouteImport } from './routes/account.downloads'
import { Route as AccountLibraryRouteImport } from './routes/account.library'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as BooksIndexRouteImport } from './routes/books.index'
import { Route as BooksSlugRouteImport } from './routes/books.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const YorlingoRoute = YorlingoRouteImport.update({
  id: '/yorlingo',
  path: '/yorlingo',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDownloadsRoute = AccountDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLibraryRoute = AccountLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/account': typeof AccountIndexRoute
  '/books': typeof BooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/bundles': typeof BundlesRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/yorlingo': typeof YorlingoRoute
  '/account/downloads': typeof AccountDownloadsRoute
  '/account/library': typeof AccountLibraryRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/books/$slug': typeof BooksSlugRoute
  '/account/': typeof AccountIndexRoute
  '/books/': typeof BooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/yorlingo'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/wishlist'
    | '/books/$slug'
    | '/account/'
    | '/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/yorlingo'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/wishlist'
    | '/books/$slug'
    | '/account'
    | '/books'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bundles'
    | '/cart'
    | '/checkout'
    | '/yorlingo'
    | '/account/downloads'
    | '/account/library'
    | '/account/orders'
    | '/account/wishlist'
    | '/books/$slug'
    | '/account/'
    | '/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  BundlesRoute: typeof BundlesRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  YorlingoRoute: typeof YorlingoRoute
  BooksSlugRoute: typeof BooksSlugRoute
  BooksIndexRoute: typeof BooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yorlingo': {
      id: '/yorlingo'
      path: '/yorlingo'
      fullPath: '/yorlingo'
      preLoaderRoute: typeof YorlingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/downloads': {
      id: '/account/downloads'
      path: '/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AccountDownloadsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/library': {
      id: '/account/library'
      path: '/library'
      fullPath: '/account/library'
      preLoaderRoute: typeof AccountLibraryRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountDownloadsRoute: typeof AccountDownloadsRoute
  AccountLibraryRoute: typeof AccountLibraryRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDownloadsRoute: AccountDownloadsRoute,
  AccountLibraryRoute: AccountLibraryRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  BundlesRoute: BundlesRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  YorlingoRoute: YorlingoRoute,
  BooksSlugRoute: BooksSlugRoute,
  BooksIndexRoute: BooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
